# Generated by Django 5.2.5 on 2025-08-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/uploads/avatar.svg', null=True, upload_to='static/uploads/'),
        ),
    ]
